### ISSUE TITLE
Could not pass event PlayerJoinEvent to FancyHolograms v1.0.6-folia

### ISSUE THREAD

**Issue by starmc63** [FancyMcPlugins/FancyHolograms#13]
[14:19:23 ERROR]: Could not pass event PlayerJoinEvent to FancyHolograms v1.0.6-folia
java.lang.IllegalStateException: Accessing entity state off owning region's thread
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.19.4.jar:git-Folia-41]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftTextDisplay.getHandle(CraftTextDisplay.java:26) ~[folia-1.19.4.jar:git-Folia-41]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftTextDisplay.getHandle(CraftTextDisplay.java:11) ~[folia-1.19.4.jar:git-Folia-41]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftEntity.isVisibleByDefault(CraftEntity.java:1033) ~[folia-1.19.4.jar:git-Folia-41]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.canSee(CraftPlayer.java:1955) ~[folia-1.19.4.jar:git-Folia-41]
        at net.minecraft.network.syncher.SynchedEntityData.refresh(SynchedEntityData.java:255) ~[?:?]
        at de.oliver.fancyholograms.Hologram.updateText(Hologram.java:118) ~[FancyHolograms-1.0.6-folia.jar:?]
        at de.oliver.fancyholograms.Hologram.spawn(Hologram.java:100) ~[FancyHolograms-1.0.6-folia.jar:?]
        at de.oliver.fancyholograms.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:21) ~[FancyHolograms-1.0.6-folia.jar:?
]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor166.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:git-Folia-41]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.19.4.jar:git-Folia-41]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.19.4.jar:git-Folia-41
]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:404) ~[folia-1.19.4.jar:git-Folia-41]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.lambda$handleAcceptedLogin$1(ServerLoginPacketListenerImpl.java:204) ~
[?:?]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.
java:504) ~[folia-1.19.4.jar:git-Folia-41]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434) ~[folia-1.19.4.ja
r:git-Folia-41]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263) ~[folia-1.19.4.
jar:git-Folia-41]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1523) ~[folia-1.19.4.jar:git-Folia-41]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Fol
ia-41]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.ja
r:git-Folia-41]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar
:git-Folia-41]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OliverSchlueter** [comment]
Yep this is indeed a bug. It will be fixed in the next version. Thank you for reporting it

**Comment by OliverSchlueter** [comment]
Should be fixed in newest release
