### ISSUE TITLE
Unable to load in Luminol server

### ISSUE THREAD

**Issue by PlaidMrdeer** [FancyMcPlugins/FancyHolograms#145]
`[15:46:53 INFO]: [FancyHolograms] Loading server plugin FancyHolograms v2.3.3
[15:46:53 ERROR]: [FancyHolograms] Error initializing plugin 'FancyHolograms-2.3.3.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/world/level/World
	at de.oliver.fancyholograms.FancyHolograms.resolveHologramAdapter(FancyHolograms.java:230) ~[FancyHolograms-2.3.3.jar:?]
	at de.oliver.fancyholograms.FancyHolograms.onLoad(FancyHolograms.java:88) ~[FancyHolograms-2.3.3.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:514) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.World
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 11 more
`

`[15:46:53 INFO]: [FancyHolograms] Enabling FancyHolograms v2.3.3
[15:46:53 ERROR]: Error occurred while enabling FancyHolograms v2.3.3 (Is it up to date?)
java.lang.NullPointerException: plugin is not initialized
	at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
	at de.oliver.fancyholograms.FancyHolograms.getHologramsManager(FancyHolograms.java:176) ~[FancyHolograms-2.3.3.jar:?]
	at de.oliver.fancyholograms.FancyHolograms.onEnable(FancyHolograms.java:136) ~[FancyHolograms-2.3.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:557) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
`

`[15:46:53 INFO]: [FancyHolograms] Disabling FancyHolograms v2.3.3
[15:46:53 ERROR]: Error occurred while disabling FancyHolograms v2.3.3
java.lang.NullPointerException: Cannot invoke "de.oliver.fancyholograms.HologramManagerImpl.saveHolograms()" because "this.hologramsManager" is null
	at de.oliver.fancyholograms.FancyHolograms.onDisable(FancyHolograms.java:151) ~[FancyHolograms-2.3.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:557) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[luminol-1.20.4.jar:git-Luminol-"5a6f4bb"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
`

**Comment by OliverSchlueter** [comment]
You need to use a mojang mapped server jar

**Comment by OliverSchlueter** [comment]
Luminol is not supported
