### ISSUE TITLE
java.lang.NullPointerException: plugin is not initialized

### ISSUE THREAD

**Issue by kangarko** [FancyMcPlugins/FancyHolograms#148]
Got this strange error running on 1.21.1 Advanced Slime Paper, a Paper fork. Let me know what more info I can provide to help us troubleshoot this.

```
java.lang.NullPointerException: plugin is not initialized
    at java.util.Objects.requireNonNull(Objects.java:259)
    at de.oliver.fancyholograms.FancyHolograms.get(FancyHolograms.java:93)
    at de.oliver.fancyholograms.storage.FlatFileHologramStorage.lambda$saveConfig$0(FlatFileHologramStorage.java:216)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1583)
```

Appreciated your help,
Matej

**Comment by kangarko** [comment]
Thank you!
