### ISSUE TITLE
Api error 

### ISSUE THREAD

**Issue by Dalynkaa** [FancyMcPlugins/FancyHolograms#30]
i get this whe try use api

[WARNING] Failed to download maven-metadata-fancyplugins-releases.xml [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download maven-metadata-maven-central.xml [https://repo1.maven.org/maven2/]
[WARNING] Failed to download maven-metadata-codemc-snapshots.xml [https://repo.codemc.io/repository/maven-snapshots/]
[WARNING] Failed to download maven-metadata-sonatype.xml [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download maven-metadata-ranull-repo-external.xml [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download maven-metadata-jitpack-repo.xml [https://jitpack.io/]
[WARNING] Failed to download maven-metadata-iridiumdevelopment.xml [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download maven-metadata-codemc-repo.xml [https://repo.codemc.org/repository/maven-public/]
[WARNING] Failed to download maven-metadata-placeholderapi.xml [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download maven-metadata-fancyplugins-releases.xml [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download maven-metadata-sonatype.xml [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download maven-metadata-ranull-repo-external.xml [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download maven-metadata-maven-central.xml [https://repo1.maven.org/maven2/]
[WARNING] Failed to download maven-metadata-codemc-snapshots.xml [https://repo.codemc.io/repository/maven-snapshots/]
[WARNING] Failed to download maven-metadata-codemc-repo.xml [https://repo.codemc.org/repository/maven-public/]
[WARNING] Failed to download maven-metadata-iridiumdevelopment.xml [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download maven-metadata-jitpack-repo.xml [https://jitpack.io/]
[WARNING] Failed to download maven-metadata-placeholderapi.xml [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download api-2.0.0.pom [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download api-2.0.0.pom [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download api-2.0.0.pom [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download api-2.0.0.pom [https://maven.enginehub.org/repo/]
[WARNING] Failed to download api-2.0.0.pom [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download api-2.0.0.pom [https://repo1.maven.org/maven2/]
[WARNING] Failed to download api-2.0.0.pom [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download api-2.0.0.pom [https://repo.codemc.io/repository/maven-snapshots/]
[WARNING] Failed to download api-2.0.0.pom [https://repo.codemc.org/repository/maven-public/]
[WARNING] Failed to download api-2.0.0.pom [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download api-2.0.0.pom [https://jitpack.io/]
[WARNING] Failed to download api-2.0.0.pom [https://repo.maven.apache.org/maven2/]
[WARNING] The POM for de.oliver:api:jar:2.0.0 is missing, no dependency information available
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://maven.enginehub.org/repo/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://repo1.maven.org/maven2/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://repo.codemc.io/repository/maven-snapshots/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://repo.codemc.org/repository/maven-public/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://jitpack.io/]
[WARNING] Failed to download implementation_1_20-2.0.0.pom [https://repo.maven.apache.org/maven2/]
[WARNING] The POM for de.oliver:implementation_1_20:jar:2.0.0 is missing, no dependency information available
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://maven.enginehub.org/repo/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://repo1.maven.org/maven2/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://repo.codemc.io/repository/maven-snapshots/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://repo.codemc.org/repository/maven-public/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://jitpack.io/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.pom [https://repo.maven.apache.org/maven2/]
[WARNING] The POM for de.oliver:implementation_1_19_4:jar:2.0.0 is missing, no dependency information available
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://maven.enginehub.org/repo/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://repo1.maven.org/maven2/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://repo.codemc.io/repository/maven-snapshots/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://repo.codemc.org/repository/maven-public/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://jitpack.io/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.pom [https://repo.maven.apache.org/maven2/]
[WARNING] The POM for de.oliver:FancyLib:jar:1.0.3-beta11 is missing, no dependency information available
[WARNING] Failed to download maven-metadata-fancyplugins-releases.xml [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download maven-metadata-maven-central.xml [https://repo1.maven.org/maven2/]
[WARNING] Failed to download maven-metadata-sonatype.xml [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download maven-metadata-ranull-repo-external.xml [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download maven-metadata-codemc-snapshots.xml [https://repo.codemc.io/repository/maven-snapshots/]
[WARNING] Failed to download maven-metadata-codemc-repo.xml [https://repo.codemc.org/repository/maven-public/]
[WARNING] Failed to download maven-metadata-jitpack-repo.xml [https://jitpack.io/]
[WARNING] Failed to download maven-metadata-iridiumdevelopment.xml [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download maven-metadata-placeholderapi.xml [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download maven-metadata-fancyplugins-releases.xml [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download maven-metadata-papermc-repo.xml [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download maven-metadata-maven-central.xml [https://repo1.maven.org/maven2/]
[WARNING] Failed to download maven-metadata-sonatype.xml [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download maven-metadata-ranull-repo-external.xml [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download maven-metadata-sk89q-repo.xml [https://maven.enginehub.org/repo/]
[WARNING] Failed to download maven-metadata-iridiumdevelopment.xml [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download maven-metadata-jitpack-repo.xml [https://jitpack.io/]
[WARNING] Failed to download maven-metadata-placeholderapi.xml [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download maven-metadata-fancyplugins-releases.xml [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download maven-metadata-papermc-repo.xml [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download maven-metadata-maven-central.xml [https://repo1.maven.org/maven2/]
[WARNING] Failed to download maven-metadata-sonatype.xml [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download maven-metadata-sk89q-repo.xml [https://maven.enginehub.org/repo/]
[WARNING] Failed to download maven-metadata-ranull-repo-external.xml [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download maven-metadata-iridiumdevelopment.xml [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download maven-metadata-jitpack-repo.xml [https://jitpack.io/]
[WARNING] Failed to download maven-metadata-placeholderapi.xml [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download api-2.0.0.jar [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download api-2.0.0.jar [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download api-2.0.0.jar [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download api-2.0.0.jar [https://maven.enginehub.org/repo/]
[WARNING] Failed to download api-2.0.0.jar [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download api-2.0.0.jar [https://repo1.maven.org/maven2/]
[WARNING] Failed to download api-2.0.0.jar [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download api-2.0.0.jar [https://repo.codemc.io/repository/maven-snapshots/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://maven.enginehub.org/repo/]
[WARNING] Failed to download api-2.0.0.jar [https://repo.codemc.org/repository/maven-public/]
[WARNING] Failed to download api-2.0.0.jar [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download api-2.0.0.jar [https://jitpack.io/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download api-2.0.0.jar [https://repo.maven.apache.org/maven2/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://repo1.maven.org/maven2/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://repo.codemc.io/repository/maven-snapshots/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://repo.codemc.org/repository/maven-public/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://jitpack.io/]
[WARNING] Failed to download implementation_1_20-2.0.0.jar [https://repo.maven.apache.org/maven2/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://oss.sonatype.org/content/groups/public/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://maven.enginehub.org/repo/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://repo.ranull.com/maven/external/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://repo1.maven.org/maven2/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://repo.extendedclip.com/content/repositories/placeholderapi/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://repo.codemc.io/repository/maven-snapshots/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://repo.codemc.org/repository/maven-public/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://nexus.iridiumdevelopment.net/repository/maven-releases/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://jitpack.io/]
[WARNING] Failed to download implementation_1_19_4-2.0.0.jar [https://repo.maven.apache.org/maven2/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.jar [https://repo.fancyplugins.de/releases/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.jar [https://repo.papermc.io/repository/maven-public/]
[WARNING] Failed to download FancyLib-1.0.3-beta11.jar [https://oss.sonatype.org/content/groups/public/]
Cannot resolve de.oliver:FancyLib:1.0.3-beta11
Cannot resolve de.oliver:implementation_1_20:2.0.0
Cannot resolve de.oliver:implementation_1_19_4:2.0.0
Cannot resolve de.oliver:api:2.0.0

**Comment by OliverSchlueter** [comment]
Do you mind sharing your gradle/maven file?

**Comment by Dalynkaa** [comment]
[pom.xml](https://github.com/FancyMcPlugins/FancyHolograms/files/12329553/pom.txt)

**Comment by Dalynkaa** [comment]
Oh, it works. Thank you!

**Comment by OliverSchlueter** [comment]
Wow cool, for now you can use that, in the next release it will be available just like you did before

**Comment by Dalynkaa** [comment]
Okay, thank you.

**Comment by Dalynkaa** [comment]
aaaaa i have another problem
java.lang.ClassCastException: class de.oliver.fancyholograms.FancyHologramsPlugin cannot be cast to class de.oliver.fancyholograms.api.FancyHologramsPlugin (de.oliver.fancyholograms.FancyHologramsPlugin is in unnamed module of loader 'FancyHolograms-2.0.0.jar' @820a688; de.oliver.fancyholograms.api.FancyHologramsPlugin is in unnamed module of loader 'SpBuild.jar' @78615847)
        at de.oliver.fancyholograms.api.FancyHologramsPlugin.get(FancyHologramsPlugin.java:14) ~[SpBuild.jar:?]
        at fun.dalynkaa.eventbuilders.events.joinEvent.onPlayerJoin(joinEvent.java:60) ~[SpBuild.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor313.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-549]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-549]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-549]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:332) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:595) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-549]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
