### ISSUE TITLE
Api bug

### ISSUE THREAD

**Issue by Dalynkaa** [FancyMcPlugins/FancyHolograms#31]
aaaaa i have another bug with api

java.lang.ClassCastException: class de.oliver.fancyholograms.FancyHologramsPlugin cannot be cast to class de.oliver.fancyholograms.api.FancyHologramsPlugin (de.oliver.fancyholograms.FancyHologramsPlugin is in unnamed module of loader 'FancyHolograms-2.0.0.jar' @820a688; de.oliver.fancyholograms.api.FancyHologramsPlugin is in unnamed module of loader 'SpBuild.jar' @78615847)
        at de.oliver.fancyholograms.api.FancyHologramsPlugin.get(FancyHologramsPlugin.java:14) ~[SpBuild.jar:?]
        at fun.dalynkaa.eventbuilders.events.joinEvent.onPlayerJoin(joinEvent.java:60) ~[SpBuild.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor313.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-549]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-549]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-549]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:332) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:595) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-549]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Dalynkaa** [comment]
my api use 
FancyHologramsPlugin.get().getHologramManager().reloadHolograms();
I need to update holograms every time because I use pictures instead of text and they sometimes become crooked.
![huge_2023-08-19_12 59 06](https://github.com/FancyMcPlugins/FancyHolograms/assets/92329662/380425fb-c8fe-4554-977e-a609dbcca277)

**Comment by OliverSchlueter** [comment]
Try to update the holograms with Hologram#refreshHologram

**Comment by Dalynkaa** [comment]
Thank you, that helped, thank you.
