### ISSUE TITLE
Unable to run create command

### ISSUE THREAD

**Issue by dogmatic69** [FancyMcPlugins/FancyHolograms#34]
Running latest 1.20.1 on papermc 

```
21.08 21:02:25 [Server] INFO dogmatic69 issued server command: /hologram create starter_explore
21.08 21:02:25 [Server] ERROR null
21.08 21:02:25 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'hologram' in plugin FancyHolograms v2.0.0
21.08 21:02:25 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
21.08 21:02:25 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
21.08 21:02:25 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-145]
21.08 21:02:25 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-145]
21.08 21:02:25 [Server] INFO at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
21.08 21:02:25 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
21.08 21:02:25 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
21.08 21:02:25 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2347) ~[?:?]
21.08 21:02:25 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2307) ~[?:?]
21.08 21:02:25 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
21.08 21:02:25 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
21.08 21:02:25 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-145]
21.08 21:02:25 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
21.08 21:02:25 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
21.08 21:02:25 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-145]
21.08 21:02:25 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-145]
21.08 21:02:25 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
21.08 21:02:25 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-145]
21.08 21:02:25 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-145]
21.08 21:02:25 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
21.08 21:02:25 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1425) ~[paper-1.20.1.jar:git-Paper-145]
21.08 21:02:25 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-145]
21.08 21:02:25 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-145]
21.08 21:02:25 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
21.08 21:02:25 [Server] INFO Caused by: java.lang.IllegalAccessError: class de.oliver.fancyholograms.version.Hologram1_20 tried to access private method 'void net.minecraft.world.entity.Display$TextDisplay.b(int)' (de.oliver.fancyholograms.version.Hologram1_20 is in unnamed module of loader 'FancyHolograms-2.0.0.jar' @55337de4; net.minecraft.world.entity.Display$TextDisplay is in unnamed module of loader java.net.URLClassLoader @22927a81)
21.08 21:02:25 [Server] INFO at de.oliver.fancyholograms.version.Hologram1_20.update(Hologram1_20.java:66) ~[FancyHolograms-2.0.0.jar:?]
21.08 21:02:25 [Server] INFO at de.oliver.fancyholograms.api.Hologram.updateHologram(Hologram.java:144) ~[FancyHolograms-2.0.0.jar:?]
21.08 21:02:25 [Server] INFO at de.oliver.fancyholograms.version.Hologram1_20.create(Hologram1_20.java:50) ~[FancyHolograms-2.0.0.jar:?]
21.08 21:02:25 [Server] INFO at de.oliver.fancyholograms.api.Hologram.createHologram(Hologram.java:130) ~[FancyHolograms-2.0.0.jar:?]
21.08 21:02:25 [Server] INFO at de.oliver.fancyholograms.commands.HologramCMD.create(HologramCMD.java:300) ~[FancyHolograms-2.0.0.jar:?]
21.08 21:02:25 [Server] INFO at de.oliver.fancyholograms.commands.HologramCMD.onCommand(HologramCMD.java:94) ~[FancyHolograms-2.0.0.jar:?]
21.08 21:02:25 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
21.08 21:02:25 [Server] INFO ... 23 more

```

**Comment by dogmatic69** [comment]
just noticed the 2.0.1 release only hours ago. that works 👍🏻
