### ISSUE TITLE
linkWithNpc bug

### ISSUE THREAD

**Issue by xdalul** [FancyMcPlugins/FancyHolograms#41]
- Using Paper 1.20.1

Well I'm having an Error with adding a Hologram to an NPC first, with the Tab-Completion and then the exectution of the Command.

Logs:

1. Tab-Completion
```
Caused by: java.lang.IncompatibleClassChangeError: Found interface de.oliver.fancynpcs.api.NpcManager, but class was expected
at de.oliver.fancyholograms.commands.HologramCMD.onTabComplete(HologramCMD.java:229) ~[FancyHolograms-2.0.1.jar:?]
at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
```

2. Execution of the Command
```
Caused by: java.lang.IncompatibleClassChangeError: Found interface de.oliver.fancynpcs.api.NpcManager, but class was expected
at de.oliver.fancyholograms.commands.HologramCMD.editLinkWithNpc(HologramCMD.java:868) ~[FancyHolograms-2.0.1.jar:?]
at de.oliver.fancyholograms.commands.HologramCMD.edit(HologramCMD.java:585) ~[FancyHolograms-2.0.1.jar:?]
at de.oliver.fancyholograms.commands.HologramCMD.onCommand(HologramCMD.java:122) ~[FancyHolograms-2.0.1.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
```

**Comment by OliverSchlueter** [comment]
Try the latest version of FancyNpcs & FancyHolograms
