### ISSUE TITLE
NPE when world is not present while saving

### ISSUE THREAD

**Issue by EinDev** [FancyMcPlugins/FancyHolograms#58]
We are getting the following NPE:
```
[15:45:12 WARN]: [FancyHolograms] Plugin FancyHolograms v2.0.4 generated an exception while executing task 134
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
   at de.oliver.fancyholograms.api.data.DisplayHologramData.write(DisplayHologramData.java:61) ~[FancyHolograms-2.0.4.jar:?]
   at de.oliver.fancyholograms.api.data.HologramData.write(HologramData.java:55) ~[FancyHolograms-2.0.4.jar:?]
   at de.oliver.fancyholograms.HologramsConfig.writeHolograms(HologramsConfig.java:92) ~[FancyHolograms-2.0.4.jar:?]
   at de.oliver.fancyholograms.HologramManagerImpl.saveHolograms(HologramManagerImpl.java:122) ~[FancyHolograms-2.0.4.jar:?]
   at de.oliver.fancyholograms.FancyHolograms.lambda$onEnable$1(FancyHolograms.java:121) ~[FancyHolograms-2.0.4.jar:?]
   at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-41]
   at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.20.4.jar:git-Pufferfish-41]
   at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.20.4.jar:?]
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
   at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
Every time the autosave starts.

*How to reproduce:*
- Create a server without any additional worlds
- Copy the holograms.yml from another server, which has a hologram in a non-standard world
- Run "/fancyholograms save"

**Comment by JasonHorkles** [comment]
What exactly are you expecting the plugin to do instead? The world doesn't exist so you'll need to manually change the world name in the storage; everything is working as expected

**Comment by EinDev** [comment]
I would usually expect a plugin to throw a (readable) error while it is loading instead of while it is saving what it loaded before. But maybe I am a bit too picky here. If you don't want to inplement this, feel free to just close this issue, no hard feelings :)

**Comment by OliverSchlueter** [comment]
I added "better error messages" on my list
