### ISSUE TITLE
Can't remove holograms in 2.0.5

### ISSUE THREAD

**Issue by Frumple** [FancyMcPlugins/FancyHolograms#60]
I'm unable to use `/hologram remove` to delete holograms in version 2.0.5. The internal exception seems to hint that the remove command is not triggering a HologramHideEvent asynchronously and thus failing.

Steps to Reproduce:
1. Create a hologram: `/hologram create asdf`
2. Remove that hologram: `/hologram remove asdf`

Expected Result:
- Hologram removed successfully

Actual Result:
- The in-game message "An internal error occurred while attempting to perform this command." appears.
- Server logs show this exception:
```
[18:15:39 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'hologram remove asdf' in de.oliver.fancyholograms.commands.HologramCMD(hologram)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.4.jar:git-Paper-365]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-365]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:444) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2234) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2194) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-365]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-365]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: HologramHideEvent may only be triggered asynchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:40) ~[paper-1.20.4.jar:git-Paper-365]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-365]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at de.oliver.fancyholograms.version.Hologram1_20_4.hide(Hologram1_20_4.java:218) ~[FancyHolograms-2.0.5.jar:?]
        at de.oliver.fancyholograms.api.Hologram.hideHologram(Hologram.java:98) ~[FancyHolograms-2.0.5.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at de.oliver.fancyholograms.api.Hologram.hideHologram(Hologram.java:105) ~[FancyHolograms-2.0.5.jar:?]
        at de.oliver.fancyholograms.commands.hologram.RemoveCMD.run(RemoveCMD.java:29) ~[FancyHolograms-2.0.5.jar:?]
        at de.oliver.fancyholograms.commands.HologramCMD.execute(HologramCMD.java:92) ~[FancyHolograms-2.0.5.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 28 more
```

**Comment by OliverSchlueter** [comment]
Fixed in dd14e0250325c9cb967fd9673ae72c74038ea798 https://jenkins.fancyplugins.de/job/FancyHolograms/51/

Thank you for reporting this issue ❤️!
